# Generated by Django 5.0.2 on 2025-09-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lanlord',
            new_name='landlord',
        ),
    ]
