# Generated by Django 5.0.2 on 2025-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_image_property_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='uploads/properties/default.jpg', upload_to='uploads/properties'),
            preserve_default=False,
        ),
    ]
