# Generated by Django 5.0.2 on 2025-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_property_image_url_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
